_extends: .github
repository:
  name: eslint-config-mocha
  description: Shareable ESLint config for projects tested with Mocha
  homepage: 'https://npm.im/@pragmatic-divops/eslint-config-mocha'
  private: false
